version: "3.8"

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_volume:
  
services:
  schedule_telegram_bot:
    build: ScheduleTelegramBot/
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
    depends_on:
      - "db"
    networks:
      - bot_network

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Yekaterinburg
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    networks:
      - bot_network
